from .test_init import HammerInitTest
from .test_single_repository import HammerRepositoryTest
from .test_submodule import HammerSubmoduleTest
from .test_multiple_projects import HammerMultipleProjectsTest
from .test_update import HammerUpdateTest
from .test_shallow_repository import HammerShallowTest
